In [11]:
from nltk.tokenize import word_tokenize,sent_tokenize,casual_tokenize
import nltk
text="AI/ML Engineer. with 10LPA"
tokens = word_tokenize(text)
tokens2=sent_tokenize(text)
tokens3=casual_tokenize(text)
print(tokens)
print(tokens2)
print(tokens3)

['AI/ML', 'Engineer', '.', 'with', '10LPA']
['AI/ML Engineer.', 'with 10LPA']
['AI', '/', 'ML', 'Engineer', '.', 'with', '10LPA']


In [16]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text = "The dog is running in the park."

tokens = word_tokenize(text)

nltk.download('stopwords')
stop_words = set(stopwords.words("english"))

filtered = [word for word in tokens if word.lower() not in stop_words]

print(filtered)

['dog', 'running', 'park', '.']


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [20]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I love AI",
    "I love Python",
    "AI loves Python Ai"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())

print(X.toarray())

['ai' 'love' 'loves' 'python']
[[1 1 0 0]
 [0 1 0 1]
 [2 0 1 1]]


In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "I love AI",
    "I love Python",
    "AI loves Python"
]

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())

print(X.toarray())

['ai' 'love' 'loves' 'python']
[[0.70710678 0.70710678 0.         0.        ]
 [0.         0.70710678 0.         0.70710678]
 [0.51785612 0.         0.68091856 0.51785612]]


In [28]:
## Text Classification

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Dataset
texts = [
    "I love AI",
    "AI is amazing",
    "I liked the movie",
    "I hate exams",
    "This movie is terrible",
    "I did not liked the movie"
]

labels = [
    "Positive",
    "Positive",
    "Positive",
    "Negative",
    "Negative",
    "Negative"
]

vectorizer=TfidfVectorizer()
x=vectorizer.fit_transform(texts)
model=LogisticRegression()
model.fit(x,labels)

## Prediction
Text=['I really liked the movie']
vec_text=vectorizer.transform(Text)
prediction=model.predict(vec_text)
print(prediction)

['Positive']


In [47]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

import torch
import torch.nn as nn
import torch.optim as optim

texts = [
    "I love AI",
    "AI is amazing",
    "Machine learning is fun",
    "Python is powerful",
    "Deep learning is interesting",

    "I hate exams",
    "This movie is terrible",
    "Worst experience ever",
    "Bad service",
    "I dislike this phone",

    "Excellent camera quality",
    "Amazing performance",
    "Fantastic product",
    "Very happy with this",
    "Great experience",

    "Awful battery life",
    "Poor quality",
    "Very disappointing",
    "Not worth buying",
    "Waste of money"
]

labels = [
    "Positive",
    "Positive",
    "Positive",
    "Positive",
    "Positive",

    "Negative",
    "Negative",
    "Negative",
    "Negative",
    "Negative",

    "Positive",
    "Positive",
    "Positive",
    "Positive",
    "Positive",

    "Negative",
    "Negative",
    "Negative",
    "Negative",
    "Negative"
]

vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(texts)

encoder=LabelEncoder()
y=encoder.fit_transform(labels)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train=torch.tensor(X_train.toarray(),dtype=torch.float32)
X_test=torch.tensor(X_test.toarray(),dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)

class TextClassifier(nn.Module):
    def __init__(self,input_size):
        super().__init__()
        self.fc1=nn.Linear(input_size,64)
        self.relu1=nn.ReLU()
        self.fc2=nn.Linear(64,32)
        self.relu2=nn.ReLU()
        self.fc3=nn.Linear(32,2)
    def forward(self,x):
        x=self.fc1(x)
        x=self.relu1(x)
        x=self.fc2(x)
        x=self.relu2(x)
        x=self.fc3(x)
        return x
input_size=X_train.shape[1]
model=TextClassifier(input_size)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs=100
for epoch in range(epochs):
    outputs=model(X_train)
    loss=criterion(outputs,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

model.eval()
with torch.no_grad():
    outputs = model(X_test)
    predicted = torch.argmax(outputs, dim=1)

accuracy = accuracy_score(
    y_test,
    predicted
)

print("Accuracy:", accuracy)

new_text = [
    "You are doing an excellent job."
]

new_vector = vectorizer.transform(new_text)

new_tensor = torch.tensor(
    new_vector.toarray(),
    dtype=torch.float32
)

model.eval()

with torch.no_grad():

    prediction = model(new_tensor)

    predicted_class = torch.argmax(prediction, dim=1)

print(encoder.inverse_transform(predicted_class.numpy()))


Epoch 10/100, Loss: 0.6878
Epoch 20/100, Loss: 0.6611
Epoch 30/100, Loss: 0.6207
Epoch 40/100, Loss: 0.5561
Epoch 50/100, Loss: 0.4609
Epoch 60/100, Loss: 0.3435
Epoch 70/100, Loss: 0.2259
Epoch 80/100, Loss: 0.1325
Epoch 90/100, Loss: 0.0720
Epoch 100/100, Loss: 0.0388
Accuracy: 0.5
['Positive']


In [95]:
## Sentiment Analysis

import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

import torch
import torch.nn as nn
import torch.optim as optim


Train_Data=pd.read_csv("C:/Users/Lenovo/OneDrive/Documents/IMDB Dataset.csv").head(200)
X=Train_Data['review']
y=Train_Data['sentiment']

vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(Train_Data['review'])
encoder=LabelEncoder()
y=encoder.fit_transform(Train_Data['sentiment'])

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train=torch.tensor(X_train.toarray(),dtype=torch.float32)
X_test=torch.tensor(X_test.toarray(),dtype=torch.float32)
y_train=torch.tensor(y_train,dtype=torch.long)
y_test=torch.tensor(y_test,dtype=torch.long)

class Sentiment_Classification(nn.Module):
    def __init__(self,input_size):
        super().__init__()
        self.fc1=nn.Linear(input_size,512)
        self.relu1=nn.ReLU()
        self.fc2=nn.Linear(512,256)
        self.relu2=nn.ReLU()
        self.fc3=nn.Linear(256,128)
        self.relu3=nn.ReLU()
        self.fc4=nn.Linear(128,64)
        self.relu4=nn.ReLU()
        self.fc5=nn.Linear(64,32)
        self.relu5=nn.ReLU()
        self.fc6=nn.Linear(32,16)
        self.relu6=nn.ReLU()
        self.fc7=nn.Linear(16,2)
    def forward(self,x):
        x=self.fc1(x)
        x=self.relu1(x)
        x=self.fc2(x)
        x=self.relu2(x)
        x=self.fc3(x)
        x=self.relu3(x)
        x=self.fc4(x)
        x=self.relu4(x)
        x=self.fc5(x)
        x=self.relu5(x)
        x=self.fc6(x)
        x=self.relu6(x)
        x=self.fc7(x)
        return x


input_size=X_train.shape[1]
model=Sentiment_Classification(input_size)   
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(), lr=0.001)

epochs=50
model.train()
for epoch in range(epochs):
    outputs=model(X_train)
    loss=criterion(outputs,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

model.eval()
with torch.no_grad():
    outputs=model(X_test)
    predicted = torch.argmax(outputs, dim=1)

accuracy = accuracy_score(
    y_test,
    predicted
)

print("Accuracy:", accuracy)

new_text=[
    'The movie is not good']
text_vector=vectorizer.transform(new_text)
text_tensor=torch.tensor(text_vector.toarray(),dtype=torch.float32)
model.eval()
with torch.no_grad():

    prediction = model(text_tensor)

    predicted_class = torch.argmax(prediction, dim=1)

print(encoder.inverse_transform(predicted_class.numpy()))
    

Epoch 10/50, Loss: 0.6805
Epoch 20/50, Loss: 0.5835
Epoch 30/50, Loss: 0.1272
Epoch 40/50, Loss: 0.0002
Epoch 50/50, Loss: 0.0000
Accuracy: 0.425
['positive']


In [110]:
## Fake News Detection

import numpy as np
import pandas as pd
from sklearn.utils import shuffle

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

import torch
import torch.nn as nn
import torch.optim as optim

Train_Data_Fake=pd.read_csv("C:/Users/Lenovo/OneDrive/Documents/Fake.csv").head(1000)
Train_Data_True=pd.read_csv("C:/Users/Lenovo/OneDrive/Documents/True.csv").head(1000)
Train_Data_True['label']=0
Train_Data_Fake['label']=1
Train_Data=pd.concat([Train_Data_Fake,Train_Data_True],ignore_index=True)
Train_Data = shuffle(Train_Data, random_state=42)

X=Train_Data.drop(columns=['label','date'])
y=Train_Data['label']

X["content"] = (
    X["title"].fillna("").astype(str) + " " +
    X["text"].fillna("").astype(str) + " " +
    X["subject"].fillna("").astype(str)
)

vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(X['content'])

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train=torch.tensor(X_train.toarray(),dtype=torch.float32)
X_test=torch.tensor(X_test.toarray(),dtype=torch.float32)
y_train=torch.tensor(y_train,dtype=torch.long)
y_test = torch.tensor(y_test.to_numpy(), dtype=torch.long)

class Fake_News_Detection(nn.Module):
    def __init__(self,input_size):
        super().__init__()
        self.fc1=nn.Linear(input_size,128)
        self.relu1=nn.ReLU()
        self.fc2=nn.Linear(128,64)
        self.relu2=nn.ReLU()
        self.fc3=nn.Linear(64,32)
        self.relu3=nn.ReLU()
        self.fc4=nn.Linear(32,2)
    def forward(self,x):
        x=self.fc1(x)
        x=self.relu1(x)
        x=self.fc2(x)
        x=self.relu2(x)
        x=self.fc3(x)
        x=self.relu3(x)
        x=self.fc4(x)
        return x
input_size=X_train.shape[1]
model=Fake_News_Detection(input_size)
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(), lr=0.001)

model.train()
epochs=100
for epoch in range(epochs):
    outputs=model(X_train)
    loss=criterion(outputs,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

model.eval()
with torch.no_grad():
    outputs=model(X_test)
    predicted = torch.argmax(outputs, dim=1)
    accuracy = accuracy_score(y_test.numpy(), predicted.numpy())
print(accuracy)

new_text=[
    'Scientists have announced that drinking five cups of coffee every day makes people live up to 150 years. The discovery has been confirmed by every major hospital worldwide, and governments are planning to make coffee mandatory for all citizens starting next month.']
text_vector=vectorizer.transform(new_text)
text_tensor=torch.tensor(text_vector.toarray(),dtype=torch.float32)
model.eval()
with torch.no_grad():

    prediction = model(text_tensor)

    predicted_class = torch.argmax(prediction, dim=1)
if predicted_class.item() == 1:
    print("Fake News")
else:
    print("True News")

#print(encoder.inverse_transform(predicted_class.numpy()))

    




Epoch 10/100, Loss: 0.6534
Epoch 20/100, Loss: 0.5482
Epoch 30/100, Loss: 0.3332
Epoch 40/100, Loss: 0.1446
Epoch 50/100, Loss: 0.0339
Epoch 60/100, Loss: 0.0060
Epoch 70/100, Loss: 0.0018
Epoch 80/100, Loss: 0.0009
Epoch 90/100, Loss: 0.0006
Epoch 100/100, Loss: 0.0005
0.9775
Fake News
