In [23]:
import torch
X=torch.tensor([1,2,3],dtype=torch.float32)
a=torch.zeros(3,3)
b=torch.ones(3,4)
c=torch.rand(3,3)
d=torch.randint(0,10,(4,3))
e=torch.eye(4)
print(X)
print(e)
print(e.shape)
print(e.size)
print(e.ndim)
print(e.device)




tensor([1., 2., 3.])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
torch.Size([4, 4])
<built-in method size of Tensor object at 0x000002A97624FDD0>
2
cpu


In [28]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
d=a-b
e=a*b
f=a/b
g=a**2
print(g)

tensor([1, 4, 9])


In [47]:
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([[5,6],[7,8]])
c=a@b
d=torch.matmul(a,b)
print(c)
print(d)
e=torch.cat((a,b))
print(e)

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [37]:
x=torch.tensor([[10,20,30],[40,50,60]])
print(x[0])
print(x[0][1])
print(x[0,1])
print(x[:,1])
print(x[1,:])

tensor([10, 20, 30])
tensor(20)
tensor(20)
tensor([20, 50])
tensor([40, 50, 60])


In [43]:
x=torch.tensor([0,1,2,3,4,5,6,7,8,9,10,11])
a=x.reshape(4,3)
print(a)
b=a.flatten()
print(b)
c=a.T
print(c)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])


In [60]:
a=torch.tensor([1,2,3],dtype=torch.float)
b=torch.tensor([4,5,6],dtype=torch.float)
c=torch.cat((a,b))
print(c)
print(c.float().mean())
print(a.mean())
print(c.max())
print(c.min())
print(c.median())
print(c.std())


tensor([1., 2., 3., 4., 5., 6.])
tensor(3.5000)
tensor(2.)
tensor(6.)
tensor(1.)
tensor(3.)
tensor(1.8708)


In [5]:
import torch
import torch.nn as  nn

X = torch.tensor([[1.0],
                  [2.0],
                  [3.0],
                  [4.0]])

y = torch.tensor([[3.0],
                  [5.0],
                  [7.0],
                  [9.0]])

model=nn.Linear(1,1)
loss_fn = nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)
epochs=1000
for epoch in range(epochs):
    predictions=model(X)
    loss=loss_fn(predictions,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

x_test = torch.tensor([[5.0]])
prediction = model(x_test)
print(prediction)


Epoch 100, Loss: 0.0296
Epoch 200, Loss: 0.0163
Epoch 300, Loss: 0.0089
Epoch 400, Loss: 0.0049
Epoch 500, Loss: 0.0027
Epoch 600, Loss: 0.0015
Epoch 700, Loss: 0.0008
Epoch 800, Loss: 0.0004
Epoch 900, Loss: 0.0002
Epoch 1000, Loss: 0.0001
tensor([[11.0198]], grad_fn=<AddmmBackward0>)


In [22]:
import torch
import torch.nn as nn

X=torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y=torch.tensor([[5.0],[10.0],[15.0],[20.0]])

model=nn.Linear(1,1)
loss_fn=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)
epochs=4000
for epoch in range(epochs):
    predictions=model(X)
    loss=loss_fn(predictions,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
print("Weight:", model.weight.item())
print("Bias:", model.bias.item())
x_test = torch.tensor([[5.0]])
prediction = model(x_test)
print(prediction)



Weight: 4.9999895095825195
Bias: 2.67293507931754e-05
tensor([[25.0000]], grad_fn=<AddmmBackward0>)


In [39]:
import torch
import torch.nn as nn
X = torch.tensor([[1.0],
                  [2.0],
                  [3.0],
                  [4.0]])

y = torch.tensor([[7.0],
                  [11.0],
                  [15.0],
                  [19.0]])

model=nn.Linear(1,1)
loss_fn=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.1)
epochs=500
for epoch in range(epochs):
    predictions=model(X)
    loss=loss_fn(predictions,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")
x_test=torch.tensor([[5.0],[6.0]])
predictions=model(x_test)
print(predictions)


Epoch 100, Loss: 0.0018
Epoch 200, Loss: 0.0000
Epoch 300, Loss: 0.0000
Epoch 400, Loss: 0.0000
Epoch 500, Loss: 0.0000
tensor([[23.0000],
        [27.0000]], grad_fn=<AddmmBackward0>)


In [49]:
import torch
import torch.nn as nn

X = torch.tensor([
    [1.0, 2.0],
    [2.0, 3.0],
    [3.0, 4.0],
    [4.0, 5.0]
])

y = torch.tensor([
    [9.0],
    [14.0],
    [19.0],
    [24.0]
])

model=nn.Linear(2,1)
loss_fn=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)
epochs=3000
for epoch in range(epochs):
    predictions=model(X)
    loss=loss_fn(predictions,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")
print(model.weight)
print(model.bias)
print(X.shape)
print(y.shape)
x_test=torch.tensor([[5.0,6.0],[6.0,7.0]])
predictions=model(x_test)
print(predictions)

Epoch 100, Loss: 0.0002
Epoch 200, Loss: 0.0001
Epoch 300, Loss: 0.0000
Epoch 400, Loss: 0.0000
Epoch 500, Loss: 0.0000
Epoch 600, Loss: 0.0000
Epoch 700, Loss: 0.0000
Epoch 800, Loss: 0.0000
Epoch 900, Loss: 0.0000
Epoch 1000, Loss: 0.0000
Epoch 1100, Loss: 0.0000
Epoch 1200, Loss: 0.0000
Epoch 1300, Loss: 0.0000
Epoch 1400, Loss: 0.0000
Epoch 1500, Loss: 0.0000
Epoch 1600, Loss: 0.0000
Epoch 1700, Loss: 0.0000
Epoch 1800, Loss: 0.0000
Epoch 1900, Loss: 0.0000
Epoch 2000, Loss: 0.0000
Epoch 2100, Loss: 0.0000
Epoch 2200, Loss: 0.0000
Epoch 2300, Loss: 0.0000
Epoch 2400, Loss: 0.0000
Epoch 2500, Loss: 0.0000
Epoch 2600, Loss: 0.0000
Epoch 2700, Loss: 0.0000
Epoch 2800, Loss: 0.0000
Epoch 2900, Loss: 0.0000
Epoch 3000, Loss: 0.0000
Parameter containing:
tensor([[1.7513, 3.2487]], requires_grad=True)
Parameter containing:
tensor([0.7513], requires_grad=True)
torch.Size([4, 2])
torch.Size([4, 1])
tensor([[29.0000],
        [34.0000]], grad_fn=<AddmmBackward0>)


In [1]:
import torch
import torch.nn as nn

class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1=nn.Conv2d(in_channels=3,out_channels=16,kernel_size=3,padding=1)
        self.conv2=nn.Conv2d(in_channels=16,out_channels=32,kernel_size=3,padding=1)
        self.relu=nn.ReLU()
        self.pool=nn.MaxPool2d(2)
        self.fc1=nn.Linear(32*8*8,128)
        self.fc2=nn.Linear(128,10)
    def forward(self,x):
        x=self.pool(self.relu(self.conv1(x)))
        x=self.pool(self.relu(self.conv2(x)))
        x=torch.flatten(x,1)
        x=self.relu(self.fc1(x))
        x=self.fc2(x)
        return x
model=CNN()
x=torch.randn(32,3,32,32)
output=model(x)
print(output.shape)



torch.Size([32, 10])
